### ISSUE TITLE
Crash on MIUI

### ISSUE THREAD

**Issue by bryanjorgeflores** [Mordtimer/chromecast_flutter#1]
Hi bro. I'm testing your implementation and I'm facing crashes in some MIUI devices. Specifically in a Poco X3.
`FATAL EXCEPTION: SysUiBg
E/AndroidRuntime(15345): Process: com.android.systemui, PID: 15345
E/AndroidRuntime(15345): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(15345):        at android.os.AsyncTask$4.done(AsyncTask.java:415)
E/AndroidRuntime(15345):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
E/AndroidRuntime(15345):        at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
E/AndroidRuntime(15345):        at java.util.concurrent.FutureTask.run(FutureTask.java:269)
E/AndroidRuntime(15345):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(15345):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(15345):        at android.os.Looper.loopOnce(Looper.java:210)
E/AndroidRuntime(15345):        at android.os.Looper.loop(Looper.java:299)
E/AndroidRuntime(15345):        at android.os.HandlerThread.run(HandlerThread.java:67)
E/AndroidRuntime(15345): Caused by: java.lang.IllegalArgumentException: The given region must intersect with the Bitmap's dimensions.
E/AndroidRuntime(15345):        at androidx.palette.graphics.Palette$Builder.setRegion(Palette.java:733)
E/AndroidRuntime(15345):        at com.android.systemui.statusbar.notification.MediaNotificationProcessor.generateArtworkPaletteBuilder(MediaNotificationProcessor.java:109)    
E/AndroidRuntime(15345):        at com.android.systemui.statusbar.notification.mediacontrol.ProcessArtworkTask.processArtwork(ProcessArtworkTask.java:102)
E/AndroidRuntime(15345):        at com.android.systemui.statusbar.notification.mediacontrol.ProcessArtworkTask.doInBackground(ProcessArtworkTask.java:77)
E/AndroidRuntime(15345):        at com.android.systemui.statusbar.notification.mediacontrol.ProcessArtworkTask.doInBackground(ProcessArtworkTask.java:25)
E/AndroidRuntime(15345):        at android.os.AsyncTask$3.call(AsyncTask.java:394)
E/AndroidRuntime(15345):        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/AndroidRuntime(15345):        ... 5 more`

**Comment by bryanjorgeflores** [comment]
I have found out a thread where they say you can setMediaSessionEnabled(false) to fix this https://github.com/google/ExoPlayer/issues/11021

**Comment by Mordtimer** [comment]
Hey, thank you for your feedback.
Did it happen only on MIUI devices? The issue from ExoPlayer seems to apply to another phones as well.
I will investigate the issue in my free time, but don't see this in any of my applications crash reports right now.

**Comment by bryanjorgeflores** [comment]
Hi buddy. The error was caused by some images that weren't available in my host. But I don't know if you could add an image by default if this error happens. For now it's working fine
